#!/bin/bash
# Usage: ./rund <testname>
# Run a .lang file using the compiler and compare output

./lang test/$1.lang out
RETVAL=$?
[ $RETVAL -ne 0 ] && exit $RETVAL

diff -q out test/$1.correct
RETVAL=$?
[ $RETVAL -eq 0 ] && echo "$1 PASSED"
[ $RETVAL -ne 0 ] && echo "$1 FAILED" && diff out test/$1.correct
exit $RETVAL
