//**************************************
// lex.h
//
// Defines global symbols used the the flex generated lexer and 
// bison generated parser.
//
// Author: Phil Howard phil.howard@oit.edu
//
#pragma once

#include <cstdio>
#include "cSymbol.h"
#include "langparse.h"   // <-- MUST come first
#include "cSymbolTable.h"
#include "cAstNode.h"

// ---------- Lexer / Parser functions ----------
int yylex();             // generated by flex
int yyparse();           // generated by bison

// ---------- Lexer globals ----------
extern int yylineno;
extern char *yytext;
extern FILE *yyin;
extern int yynerrs;

extern cAstNode *yyast_root;
//extern YYSTYPE yylval;
