#pragma once
//**************************************
// lex.h
//
// Defines global symbols used the the flex generated lexer and 
// bison generated parser.
//
// Author: Phil Howard phil.howard@oit.edu
//

#include "cSymbol.h"
//#include "cSymbolTable.h"
#include "cAstNode.h"


// lexer function generated by flex
int yylex();
int yyparse();                          // parsing function

extern char *yytext;        // text of the current token
extern int yylineno;        // line number of current token
extern int yynerrs;                     // Num of compile errors
extern FILE *yyin;                      // FILE pointer for input
extern cAstNode *yyast_root;            // root of AST

/*typedef union
{
    int token;
    cSymbol *symbol;
} yylval_t;*/

// extern yylval_t yylval;
extern char *yytext;        // text of the current token
extern int yylineno;        // line number of current token
extern FILE *yyin;          // input file for lexer
//extern int g_insert;        // global to indicate that symbols should be 
                            // inserted into the symbol table
extern int g_local;         // global to indicate to do local lookups

#ifndef LEX_H
#define LEX_H

#include "cSymbol.h"

typedef struct
{
    cSymbol *symbol;
} yylval_t;

extern yylval_t yylval;

#endif

